apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ela-node-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ela-node-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ela-node-reader
subjects:
- kind: ServiceAccount
  name: default  # Or the name of your specific service account
  namespace: app-pod-infos-ns