apiVersion: v1
kind: Service
metadata:
  name: az-checker-service
  namespace: app-pod-infos-ns
spec:
  selector:
    app: az-checker-app
  ports:
    - protocol: TCP
      port: 80       # Port the Service listens on
      targetPort: 8080 # Port the container is listening on